### PR TITLE
add cli

### PR DESCRIPTION
**Pull request by juliomatcom**
:cl:  add a **cli** to deprikat

### CODE REVIEW

**Comment by juliomatcom** [comment]
if you prefer the PR against other branch tell me :dart:

**Comment by alvaropinot** [comment]
lint that code @juliomatcom, codeclimate is complaining about a missing space :)

https://codeclimate.com/github/alvaropinot/deprikat/pull/18

**Comment by alvaropinot** [comment]
I've integrated #20 into develop with a simpler linter config. Now your new `cli` and any new folder should be linted by default. Update your upstream and your PR :D

**Comment by alvaropinot** [comment]
LGTM nice work! :D

**Pull request merged**
